version: '3.8'
services:
  db:
    image: postgres:9.6-alpine
    ports:
      - $DB_PORT:5432
    environment:
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_DATABASE
    restart: always
    volumes:
      - ./docker/data/postgres:/var/lib/postgresql/data
    networks:
      - overlay
    env_file:
      - .env

  app:
    build: .
    volumes:
      - .:/app
    command: 'docker/scripts/start-server.sh'
    ports:
      - $APP_PORT:3000
    environment:
      DB_USERNAME: $DB_USERNAME
      DB_PASSWORD: $DB_PASSWORD
      DB_DATABASE: $DB_DATABASE
      DB_DATABASE_HOST: $DB_HOST
    tty: true
    stdin_open: true
    networks:
      - overlay
    env_file:
      - .env

networks:
  overlay:
